version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    "subtitleedit",
    "subtitleedit.desktop"
    ]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "subtitleedit.png"
    ]
SPDX-FileCopyrightText = "Nikolaj Olsson"
SPDX-License-Identifier = "GPL-3.0-only"
