[linux-vfio]
source = "git"
git = "https://gitlab.archlinux.org/archlinux/packaging/packages/linux.git"
include_regex = '[0-9\.]+\.arch[0-9]-[0-9]'
from_pattern = '\.arch[0-9]-[0-9]$'
to_pattern = ''
