version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".gitignore",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "2026 HurricanePootis <hurricanepootis@protonmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
	"steamcmd",
]
SPDX-FileCopyrightText = "2015 Alexandre Detiste <alexandre@detiste.be>"
SPDX-License-Identifier = "MIT"
